### ISSUE TITLE
Possible hardware issue

### ISSUE THREAD

**Issue by An0u** [ichiriac/ubuntu-smart-fan#2]
Output of debug 
```Looking for sensors

## hwmon0 :
  - name = acpitz
  - temp1_crit = 127000
  - temp1_input = 52000
  - temp2_crit = 105000
  - temp2_input = 53000
  - uevent = 

## hwmon1 :
  - fan1_input = 5961
  - name = thinkpad
  - pwm1 = 255
  - pwm1_enable = 2
fs.js:114
    throw err;
    ^

Error: ENXIO: no such device or address, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at /usr/local/lib/node_modules/ubuntu-smart-fan/index.js:53:30
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/ubuntu-smart-fan/index.js:49:18
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/ubuntu-smart-fan/index.js:43:9
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by ichiriac** [comment]
Hi @An0u, I don't have time to investigate it, any pull request on this is welcome
